version: "3"

services:
  nginx-proxy:
    image: my-nginx
    ports:
      - "1338:80"
    volumes:
      - ./src:/usr/share/nginx/html
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./ngx_security_headers:/etc/nginx/ngx_security_headers
  node-test:
    image: node-test
    hostname: node-test
    ports:
      - "1337:1337"
